name: "Frak Lopez"
headerTag: "Developer"
description: "I am a developer."

twitter: "@dev_vine"
email: "fraklopez@gmail.com"

workDescription: "I enjoy the thrill and excitement that comes from developing ideas and giving them digital life."

pygments: true